version: '3'

services:
  myDb:
    image: postgres:15.3
    container_name: pass-generator
    restart: always
    environment:
      POSTGRES_USER: lido
      POSTGRES_PASSWORD: Aleisha
      POSTGRES_DB: Password-db
    ports:
      - 5435:5435
    volumes:
      - ./postgres/var/lib/postgresql/data
